name: 'Setup Rust'
description: 'Setup Rust toolchain with caching'

inputs:
  toolchain:
    description: 'Rust toolchain to install'
    required: false
    default: 'stable'
  targets:
    description: 'Additional targets to install'
    required: false
    default: ''
  components:
    description: 'Additional components to install'
    required: false
    default: ''
  cache-key:
    description: 'Additional cache key suffix'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
    
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ inputs.toolchain }}-${{ inputs.cache-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.toolchain }}-${{ inputs.cache-key }}-
          ${{ runner.os }}-cargo-${{ inputs.toolchain }}-
          ${{ runner.os }}-cargo-