[package]
name = "mocks"
version = "0.1.0"
edition = "2021"
authors = ["codemountains"]
description = "Get a mock REST APIs with zero coding within seconds."

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.17", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
