coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 3%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 3%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "**/*.rs:#[cfg(test)]"
  - "**/*.rs:mod tests"
  - "docs/*"
  - "runn-e2e/*"
