coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 3%
        if_ci_failed: error
    patch:
      target: 80%
      threshold: 3%
      if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "docs/*"
  - "runn-e2e/*"
  - "scripts/*"

parsers:
  rust:
    ignore:
      # cfg(test)で囲まれたコードブロック
      - ".*#\\[cfg\\(test\\)\\].*"
      # テスト関数
      - ".*#\\[test\\].*"
      # ベンチマーク関数
      - ".*#\\[bench\\].*"
      # should_panicテスト
      - ".*#\\[should_panic.*\\].*"
