coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 3%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 3%
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "docs/*"
  - "runn-e2e/*"
  - "scripts/*"
