on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Publish to crates.io

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml

  publish:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check version change
        id: version_check
        run: |
          PREV_VERSION=$(git show HEAD^:Cargo.toml | grep "^version = " | cut -d'"' -f2)
          CURRENT_VERSION=$(grep "^version = " Cargo.toml | cut -d'"' -f2)
          if [ "$PREV_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "Version changed from $PREV_VERSION to $CURRENT_VERSION"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version not changed"
          fi

      - name: Trigger manual publish workflow
        if: steps.version_check.outputs.version_changed == 'true'
        run: |
          gh workflow run manual-publish-to-cratesio.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
