name: Release

on:
  push:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yml

  create-release:
    needs: test-and-lint
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version_changed: ${{ steps.check_version.outputs.version_changed }}
      tag_exists: ${{ steps.check_tag.outputs.tag_exists }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current version
      id: get_version
      run: |
        CURRENT_VERSION=$(grep "^version = " Cargo.toml | cut -d'"' -f2)
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "tag=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $CURRENT_VERSION"

    - name: Setup Node.js for version sync
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check if version changed
      id: check_version
      run: |
        CURRENT_VERSION="${{ steps.get_version.outputs.version }}"
        
        # Get the previous version from the last commit
        PREVIOUS_VERSION=$(git show HEAD~1:Cargo.toml | grep "^version = " | cut -d'"' -f2 2>/dev/null || echo "")
        
        echo "Previous version: $PREVIOUS_VERSION"
        echo "Current version: $CURRENT_VERSION"
        
        if [ -n "$PREVIOUS_VERSION" ] && [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
        else
          echo "version_changed=false" >> $GITHUB_OUTPUT
          echo "Version unchanged: $CURRENT_VERSION"
        fi

    - name: Check version consistency
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        node scripts/sync-versions.js check

    - name: Check if tag exists
      id: check_tag
      if: steps.check_version.outputs.version_changed == 'true'
      run: |
        TAG="${{ steps.get_version.outputs.version }}"
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "tag_exists=true" >> $GITHUB_OUTPUT
          echo "Tag $TAG already exists"
        else
          echo "tag_exists=false" >> $GITHUB_OUTPUT
          echo "Tag $TAG does not exist"
        fi

    - name: Create GitHub Release
      if: steps.check_version.outputs.version_changed == 'true' && steps.check_tag.outputs.tag_exists == 'false'
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ${{ steps.get_version.outputs.version }}
        generate_release_notes: true
        draft: true
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Release
      if: steps.check_version.outputs.version_changed == 'true' && steps.check_tag.outputs.tag_exists == 'false'
      run: |
        TAG="${{ steps.get_version.outputs.version }}"
        gh release edit "$TAG" --draft=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-cratesio:
    needs: create-release
    if: needs.create-release.outputs.version_changed == 'true' && needs.create-release.outputs.tag_exists == 'false'
    uses: ./.github/workflows/publish-to-cratesio.yml
    with:
      version: ${{ needs.create-release.outputs.version }}
      dry_run: false
    secrets: inherit

  publish-to-npm:
    needs: create-release
    if: needs.create-release.outputs.version_changed == 'true' && needs.create-release.outputs.tag_exists == 'false'
    uses: ./.github/workflows/publish-to-npm.yml
    with:
      version: ${{ needs.create-release.outputs.version }}
      dry_run: false
    secrets: inherit
