name: Test and Lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    
    - name: Run tests
      run: cargo test
    
    - name: Check formatting
      run: cargo fmt -- --check
