name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        components: rustfmt, clippy
    
    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run unit tests
      run: cargo test --all-features --workspace

    - name: Run integration tests
      run: cargo test --test '*' --all-features

    - name: Check MSRV compatibility
      run: |
        cargo install cargo-msrv --locked
        cargo msrv verify

    - name: Setup Node.js for version check
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Check version consistency
      run: |
        node scripts/sync-versions.js check
